### PR TITLE
Update docker-compose.yaml

### PR DESCRIPTION
**Pull request by just5ky**
Added timezone and host time inside docker container

#### Before
image

#### After
image

### CODE REVIEW

**Comment by gabe565** [comment]
Great idea. Thank you!

**Comment by just5ky** [comment]
@bruvv if you remove the timestamp volume, does it work?

**Comment by bruvv** [comment]
@just5ky correct with just `      - "/etc/localtime:/etc/localtime:ro" # Use host's localtime, mounted read-only` it works

**Comment by just5ky** [comment]
I can submit another PR and add a comment next to it.

**Comment by gabe565** [comment]
Hmm looks like Mac's behave similarly. `/etc/localtome` would work fine though!

**Comment by gabe565** [comment]
The container also supports the `TZ` env. Maybe manual configuration would make sense?

**Comment by gabe565** [comment]
Seems to work fine with only `/etc/localtime`, so I removed the `/etc/timezone` volume bind for now. Would you guys be opposed to me removing that volumes and adding something like this instead? It's less automatic, but I feel it might be more compatible
```yaml
environment:
  TZ: UTC
```

**Comment by just5ky** [comment]
I should have thought about `TZ` env
I am all for it.

**Pull request merged**
